### DISCUSSION TITLE
0.4.1a

### DISCUSSION THREAD

**Discussion by alienatedsec** [alienatedsec/yi-hack-v5#290] [Announcements]
## What's Changed
* Roleo testing merge for pre-release by @alienatedsec in https://github.com/alienatedsec/yi-hack-v5/pull/289

Changes by @roleoroleo 
* [Restore feature to edit config files](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/9a8871666fe542898cce1cc3c0dd5d5e5dd36e6f)
* [Add flag to decrease binary size](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/5c0e1f6d39f53edc84593ff1727380437532e75b)
* [Remove old patch](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/381b840bf043e8c02331fb0d95ff4e19e679093e)
* [Decrease RTP packet length](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/f5e97ce30d01cf6b41081c7f2a4ca3741f19bab9)
* [Improve sync/async read](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/9897afc09df6e08870401341e53262bc5a3be558)
* [Update gitignore](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/d29169e3cceb7765e9ffb182a3663b3ec51bfc0b)
* [New features: disable, force low and already running](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/70a78bd9ba275af44f93c4d11928b92af4a6d87c)
* [Remove unused settings from config files](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/d19971d4933f1addc75192ad786e3a120ba02729)
* [Add options to disable snapshot and force low res](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/c7034e24c88b105183cdb1b802ec9d4445b6d963)
* [Remove unused mqtt options](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/fcb3bc313482d30c3293fb8a5830f678ba4ba565)
* [Fix and improve h264grabber](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/2dc4cfa895413867f7bdc3b71e594c322d47401c)
* [Fix system.conf parameters](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/6ce47e243809f55bf4df60f9f5b5eadec930b2ad)
* [Remove ai_human_detection and restore baby_crying](https://github.com/alienatedsec/yi-hack-v5/pull/289/commits/a309b2aac774f2cb39f34969d7721f9c6df2a02a)

Changes by @alienatedsec 
* [Wi-Fi Recovery Partition](https://github.com/alienatedsec/yi-hack-v5/commit/25db09f312d3f05f5ed64c81ec9f4ad5a5167f64) - Instructions to be issued soon.

**Full Changelog**: https://github.com/alienatedsec/yi-hack-v5/compare/0.4.0...0.4.1a

<hr /><em>This discussion was created from the release <a href='https://github.com/alienatedsec/yi-hack-v5/releases/tag/0.4.1a'>0.4.1a</a>.</em>

**Comment by InstantCassette** [comment]
Alright, this firmware is a BIG difference for me in regard to RTSP streams to my Frigate docker. Whereas 0.3.8 and 0.4.0 would corrupt & freeze (causing FFmpeg to crash on Frigate) this one is **very** responsive and stable. 👍

**Reply by roleoroleo** [reply]
Please, test the stream with audio and let us know if it's stable.

**Reply by InstantCassette** [reply]
Testing on my 4 Yi Home 1080p (48US) Audio seems fine aside from the occasional crackle.

For Frigate, I did have to do a audio re-encode to make it work with webrtc. MP4 & MSE was working fine with original aac audio. Also to make any of the clips/events render correctly in the frigate UI it also needs the audio transcode, otherwise it will just freeze and not play the clip. Latency is entirely dependant on ffmpeg configuration.

```
go2rtc:
  webrtc:
    candidates:
      - YOUR.DNS.OR.IP:8555
  streams:
    Stream0_SD_Direct:
      - rtsp://USER:PASS@CAMERA.IP:554/ch0_1.h264
    Stream0_SD:
      - "ffmpeg:Stream0_SD_Direct#video=copy#hardware#audio=aac#audio=opus#async"
    Stream0_HD_Direct:
      - rtsp://USER:PASS@CAMERA.IP:554/ch0_0.h264
    Stream0_HD:
      - "ffmpeg:Stream0_HD_Direct#video=copy#hardware#audio=aac#audio=opus#async"
    
cameras:
  Camera0:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://YOUR.DNS.OR.IP:8554/Stream0_SD
          roles:
            - detect
        - path: rtsp://YOUR.DNS.OR.IP:8554/Stream0_HD
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
    record:
      enabled: True
    snapshots:
      enabled: True
    live:
      stream_name: Stream0_HD
```
(fixed incorrect indentation, thx @waleed-alharthi)
